version: '3.4'
services:
  spectrum:
    image: spectrum2/spectrum:latest
    container_name: spectrum
    ports:
      - 8080:8080
    volumes:
      - ./tests/xmpp/configuration/transports:/etc/spectrum2/transports:ro
      - ./tests/xmpp/data:/var/lib/spectrum2
    depends_on:
      - "prosody"
  prosody:
    image: prosody/prosody:latest
    container_name: prosody
    ports: 
      - 5222:5222
      - 5347:5347
    environment:
      - LOCAL=admin
      - DOMAIN=localhost
      - PASSWORD=secret
    volumes:
      - ./tests/prosody/configuration:/etc/prosody:ro
      - ./tests/prosody/modules:/usr/lib/prosody-modules:ro
      - ./tests/prosody/data:/var/lib/prosody
